name: CI-Polaris-1
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Polaris Scan
        uses: synopsys-sig/synopsys-action@v1.11.0
        env:
          DETECT_DETECTOR_SEARCH_DEPTH: 10
          DETECT_ACCURACY_REQUIRED: NONE
          BRIDGE_POLARIS_ASSESSMENT_MODE: SOURCE_UPLOAD
        with:
        
          ### SCANNING: Required fields
          polaris_server_url: ${{ vars.POLARIS_SERVERURL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_assessment_types: "SCA,SAST"
          
          ### SCANNING: Optional fields
          polaris_application_name: AJW-${{ github.event.repository.name }}
          polaris_project_name: ${{ github.event.repository.name }}
          
          ### PULL REQUEST COMMENTS: Uncomment below to enable
          #polaris_prComment_enabled: true 
          #github_token: ${{ secrets.GIT_PAT }} # Required when PR comments is enabled

          ### SARIF report parameters
          #polaris_reports_sarif_create: true
          #polaris_upload_sarif_report: true
